name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure script has execute permissions
        run: chmod +x app.py

      - name: Run Python script with debugging
        run: python -u app.py